---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: invalidpsp
spec:
  privileged: false
  allowPrivilegeEscalation: true
  allowedHostPaths:
    - pathPrefix: "/var/vcap"
  volumes:
    - '*'
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:invalidpsp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - invalidpsp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:invalidpsp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:invalidpsp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters

